= Math

These are math-related utilities.

== Libraries

:SafeMath: pass:normal[xref:#SafeMath[`SafeMath`]]
:add: pass:normal[xref:#SafeMath-add-uint256-uint256-[`add`]]
:sub: pass:normal[xref:#SafeMath-sub-uint256-uint256-[`sub`]]
:sub: pass:normal[xref:#SafeMath-sub-uint256-uint256-string-[`sub`]]
:mul: pass:normal[xref:#SafeMath-mul-uint256-uint256-[`mul`]]
:div: pass:normal[xref:#SafeMath-div-uint256-uint256-[`div`]]
:div: pass:normal[xref:#SafeMath-div-uint256-uint256-string-[`div`]]
:mod: pass:normal[xref:#SafeMath-mod-uint256-uint256-[`mod`]]
:mod: pass:normal[xref:#SafeMath-mod-uint256-uint256-string-[`mod`]]

[[SafeMath]]
== `SafeMath`

Wrappers over Solidity's arithmetic operations with added overflow
checks.

Arithmetic operations in Solidity wrap on overflow. This can easily result
in bugs, because programmers usually assume that an overflow raises an
error, which is the standard behavior in high level programming languages.
`SafeMath` restores this intuition by reverting the transaction when an
operation overflows.

Using this library instead of the unchecked operations eliminates an entire
class of bugs, so it's recommended to use it always.


- xref:#SafeMath-add-uint256-uint256-[add(uint256,uint256)]
- xref:#SafeMath-sub-uint256-uint256-[sub(uint256,uint256)]
- xref:#SafeMath-sub-uint256-uint256-string-[sub(uint256,uint256,string)]
- xref:#SafeMath-mul-uint256-uint256-[mul(uint256,uint256)]
- xref:#SafeMath-div-uint256-uint256-[div(uint256,uint256)]
- xref:#SafeMath-div-uint256-uint256-string-[div(uint256,uint256,string)]
- xref:#SafeMath-mod-uint256-uint256-[mod(uint256,uint256)]
- xref:#SafeMath-mod-uint256-uint256-string-[mod(uint256,uint256,string)]


[[SafeMath-add-uint256-uint256-]]
=== add(uint256 a, uint256 b) → uint256

Returns the addition of two unsigned integers, reverting on
overflow.

Counterpart to Solidity's `+` operator.

Requirements:
- Addition cannot overflow.

[[SafeMath-sub-uint256-uint256-]]
=== sub(uint256 a, uint256 b) → uint256

Returns the subtraction of two unsigned integers, reverting on
overflow (when the result is negative).

Counterpart to Solidity's `-` operator.

Requirements:
- Subtraction cannot overflow.

[[SafeMath-sub-uint256-uint256-string-]]
=== sub(uint256 a, uint256 b, string errorMessage) → uint256

Returns the subtraction of two unsigned integers, reverting with custom message on
overflow (when the result is negative).

Counterpart to Solidity's `-` operator.

Requirements:
- Subtraction cannot overflow.

_Available since v2.4.0._

[[SafeMath-mul-uint256-uint256-]]
=== mul(uint256 a, uint256 b) → uint256

Returns the multiplication of two unsigned integers, reverting on
overflow.

Counterpart to Solidity's `*` operator.

Requirements:
- Multiplication cannot overflow.

[[SafeMath-div-uint256-uint256-]]
=== div(uint256 a, uint256 b) → uint256

Returns the integer division of two unsigned integers. Reverts on
division by zero. The result is rounded towards zero.

Counterpart to Solidity's `/` operator. Note: this function uses a
`revert` opcode (which leaves remaining gas untouched) while Solidity
uses an invalid opcode to revert (consuming all remaining gas).

Requirements:
- The divisor cannot be zero.

[[SafeMath-div-uint256-uint256-string-]]
=== div(uint256 a, uint256 b, string errorMessage) → uint256

Returns the integer division of two unsigned integers. Reverts with custom message on
division by zero. The result is rounded towards zero.

Counterpart to Solidity's `/` operator. Note: this function uses a
`revert` opcode (which leaves remaining gas untouched) while Solidity
uses an invalid opcode to revert (consuming all remaining gas).

Requirements:
- The divisor cannot be zero.

_Available since v2.4.0._

[[SafeMath-mod-uint256-uint256-]]
=== mod(uint256 a, uint256 b) → uint256

Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
Reverts when dividing by zero.

Counterpart to Solidity's `%` operator. This function uses a `revert`
opcode (which leaves remaining gas untouched) while Solidity uses an
invalid opcode to revert (consuming all remaining gas).

Requirements:
- The divisor cannot be zero.

[[SafeMath-mod-uint256-uint256-string-]]
=== mod(uint256 a, uint256 b, string errorMessage) → uint256

Returns the remainder of dividing two unsigned integers. (unsigned integer modulo),
Reverts with custom message when dividing by zero.

Counterpart to Solidity's `%` operator. This function uses a `revert`
opcode (which leaves remaining gas untouched) while Solidity uses an
invalid opcode to revert (consuming all remaining gas).

Requirements:
- The divisor cannot be zero.

_Available since v2.4.0._



:Math: pass:normal[xref:#Math[`Math`]]
:max: pass:normal[xref:#Math-max-uint256-uint256-[`max`]]
:min: pass:normal[xref:#Math-min-uint256-uint256-[`min`]]
:average: pass:normal[xref:#Math-average-uint256-uint256-[`average`]]

[[Math]]
== `Math`

Standard math utilities missing in the Solidity language.


- xref:#Math-max-uint256-uint256-[max(uint256,uint256)]
- xref:#Math-min-uint256-uint256-[min(uint256,uint256)]
- xref:#Math-average-uint256-uint256-[average(uint256,uint256)]


[[Math-max-uint256-uint256-]]
=== max(uint256 a, uint256 b) → uint256

Returns the largest of two numbers.

[[Math-min-uint256-uint256-]]
=== min(uint256 a, uint256 b) → uint256

Returns the smallest of two numbers.

[[Math-average-uint256-uint256-]]
=== average(uint256 a, uint256 b) → uint256

Returns the average of two numbers. The result is rounded towards
zero.


