= Utilities

Miscellaneous contracts containing utility functions, often related to working with different data types.

== Contracts

:Address: pass:normal[xref:#Address[`Address`]]
:isContract: pass:normal[xref:#Address-isContract-address-[`isContract`]]
:toPayable: pass:normal[xref:#Address-toPayable-address-[`toPayable`]]
:sendValue: pass:normal[xref:#Address-sendValue-address-payable-uint256-[`sendValue`]]

[[Address]]
== `Address`

Collection of functions related to the address type


- xref:#Address-isContract-address-[isContract(address)]
- xref:#Address-toPayable-address-[toPayable(address)]
- xref:#Address-sendValue-address-payable-uint256-[sendValue(address payable,uint256)]


[[Address-isContract-address-]]
=== isContract(address account) → bool

Returns true if `account` is a contract.

[IMPORTANT]
====
It is unsafe to assume that an address for which this function returns
false is an externally-owned account (EOA) and not a contract.

Among others, `isContract` will return false for the following 
types of addresses:

- an externally-owned account
- a contract in construction
- an address where a contract will be created
- an address where a contract lived, but was destroyed
====

[[Address-toPayable-address-]]
=== toPayable(address account) → address payable

Converts an `address` into `address payable`. Note that this is
simply a type cast: the actual underlying value is not changed.

_Available since v2.4.0._

[[Address-sendValue-address-payable-uint256-]]
=== sendValue(address payable recipient, uint256 amount)

Replacement for Solidity's `transfer`: sends `amount` wei to
`recipient`, forwarding all available gas and reverting on errors.

https://eips.ethereum.org/EIPS/eip-1884[EIP1884] increases the gas cost
of certain opcodes, possibly making contracts go over the 2300 gas limit
imposed by `transfer`, making them unable to receive funds via
`transfer`. {sendValue} removes this limitation.

https://diligence.consensys.net/posts/2019/09/stop-using-soliditys-transfer-now/[Learn more].

IMPORTANT: because control is transferred to `recipient`, care must be
taken to not create reentrancy vulnerabilities. Consider using
{ReentrancyGuard} or the
https://solidity.readthedocs.io/en/v0.5.11/security-considerations.html#use-the-checks-effects-interactions-pattern[checks-effects-interactions pattern].

_Available since v2.4.0._



:SafeCast: pass:normal[xref:#SafeCast[`SafeCast`]]
:toUint128: pass:normal[xref:#SafeCast-toUint128-uint256-[`toUint128`]]
:toUint64: pass:normal[xref:#SafeCast-toUint64-uint256-[`toUint64`]]
:toUint32: pass:normal[xref:#SafeCast-toUint32-uint256-[`toUint32`]]
:toUint16: pass:normal[xref:#SafeCast-toUint16-uint256-[`toUint16`]]
:toUint8: pass:normal[xref:#SafeCast-toUint8-uint256-[`toUint8`]]

[[SafeCast]]
== `SafeCast`

Wrappers over Solidity's uintXX casting operators with added overflow
checks.

Downcasting from uint256 in Solidity does not revert on overflow. This can
easily result in undesired exploitation or bugs, since developers usually
assume that overflows raise errors. `SafeCast` restores this intuition by
reverting the transaction when such an operation overflows.

Using this library instead of the unchecked operations eliminates an entire
class of bugs, so it's recommended to use it always.

Can be combined with {SafeMath} to extend it to smaller types, by performing
all math on `uint256` and then downcasting.

_Available since v2.5.0._


- xref:#SafeCast-toUint128-uint256-[toUint128(uint256)]
- xref:#SafeCast-toUint64-uint256-[toUint64(uint256)]
- xref:#SafeCast-toUint32-uint256-[toUint32(uint256)]
- xref:#SafeCast-toUint16-uint256-[toUint16(uint256)]
- xref:#SafeCast-toUint8-uint256-[toUint8(uint256)]


[[SafeCast-toUint128-uint256-]]
=== toUint128(uint256 value) → uint128

Returns the downcasted uint128 from uint256, reverting on
overflow (when the input is greater than largest uint128).

Counterpart to Solidity's `uint128` operator.

Requirements:

- input must fit into 128 bits

[[SafeCast-toUint64-uint256-]]
=== toUint64(uint256 value) → uint64

Returns the downcasted uint64 from uint256, reverting on
overflow (when the input is greater than largest uint64).

Counterpart to Solidity's `uint64` operator.

Requirements:

- input must fit into 64 bits

[[SafeCast-toUint32-uint256-]]
=== toUint32(uint256 value) → uint32

Returns the downcasted uint32 from uint256, reverting on
overflow (when the input is greater than largest uint32).

Counterpart to Solidity's `uint32` operator.

Requirements:

- input must fit into 32 bits

[[SafeCast-toUint16-uint256-]]
=== toUint16(uint256 value) → uint16

Returns the downcasted uint16 from uint256, reverting on
overflow (when the input is greater than largest uint16).

Counterpart to Solidity's `uint16` operator.

Requirements:

- input must fit into 16 bits

[[SafeCast-toUint8-uint256-]]
=== toUint8(uint256 value) → uint8

Returns the downcasted uint8 from uint256, reverting on
overflow (when the input is greater than largest uint8).

Counterpart to Solidity's `uint8` operator.

Requirements:

- input must fit into 8 bits.



:Arrays: pass:normal[xref:#Arrays[`Arrays`]]
:findUpperBound: pass:normal[xref:#Arrays-findUpperBound-uint256---uint256-[`findUpperBound`]]

[[Arrays]]
== `Arrays`

Collection of functions related to array types.


- xref:#Arrays-findUpperBound-uint256---uint256-[findUpperBound(uint256[],uint256)]


[[Arrays-findUpperBound-uint256---uint256-]]
=== findUpperBound(uint256[] array, uint256 element) → uint256

Searches a sorted `array` and returns the first index that contains
a value greater or equal to `element`. If no such index exists (i.e. all
values in the array are strictly less than `element`), the array length is
returned. Time complexity O(log n).

`array` is expected to be sorted in ascending order, and to contain no
repeated elements.



:EnumerableSet: pass:normal[xref:#EnumerableSet[`EnumerableSet`]]
:add: pass:normal[xref:#EnumerableSet-add-struct-EnumerableSet-AddressSet-address-[`add`]]
:remove: pass:normal[xref:#EnumerableSet-remove-struct-EnumerableSet-AddressSet-address-[`remove`]]
:contains: pass:normal[xref:#EnumerableSet-contains-struct-EnumerableSet-AddressSet-address-[`contains`]]
:enumerate: pass:normal[xref:#EnumerableSet-enumerate-struct-EnumerableSet-AddressSet-[`enumerate`]]
:length: pass:normal[xref:#EnumerableSet-length-struct-EnumerableSet-AddressSet-[`length`]]
:get: pass:normal[xref:#EnumerableSet-get-struct-EnumerableSet-AddressSet-uint256-[`get`]]

[[EnumerableSet]]
== `EnumerableSet`

Library for managing
https://en.wikipedia.org/wiki/Set_(abstract_data_type)[sets] of primitive
types.

Sets have the following properties:

- Elements are added, removed, and checked for existence in constant time
(O(1)).
- Elements are enumerated in O(n). No guarantees are made on the ordering.

As of v2.5.0, only `address` sets are supported.

Include with `using EnumerableSet for EnumerableSet.AddressSet;`.

_Available since v2.5.0._




- xref:#EnumerableSet-add-struct-EnumerableSet-AddressSet-address-[add(struct EnumerableSet.AddressSet,address)]
- xref:#EnumerableSet-remove-struct-EnumerableSet-AddressSet-address-[remove(struct EnumerableSet.AddressSet,address)]
- xref:#EnumerableSet-contains-struct-EnumerableSet-AddressSet-address-[contains(struct EnumerableSet.AddressSet,address)]
- xref:#EnumerableSet-enumerate-struct-EnumerableSet-AddressSet-[enumerate(struct EnumerableSet.AddressSet)]
- xref:#EnumerableSet-length-struct-EnumerableSet-AddressSet-[length(struct EnumerableSet.AddressSet)]
- xref:#EnumerableSet-get-struct-EnumerableSet-AddressSet-uint256-[get(struct EnumerableSet.AddressSet,uint256)]


[[EnumerableSet-add-struct-EnumerableSet-AddressSet-address-]]
=== add(struct EnumerableSet.AddressSet set, address value) → bool

Add a value to a set. O(1).
Returns false if the value was already in the set.

[[EnumerableSet-remove-struct-EnumerableSet-AddressSet-address-]]
=== remove(struct EnumerableSet.AddressSet set, address value) → bool

Removes a value from a set. O(1).
Returns false if the value was not present in the set.

[[EnumerableSet-contains-struct-EnumerableSet-AddressSet-address-]]
=== contains(struct EnumerableSet.AddressSet set, address value) → bool

Returns true if the value is in the set. O(1).

[[EnumerableSet-enumerate-struct-EnumerableSet-AddressSet-]]
=== enumerate(struct EnumerableSet.AddressSet set) → address[]

Returns an array with all values in the set. O(N).
Note that there are no guarantees on the ordering of values inside the
array, and it may change when more values are added or removed.
WARNING: This function may run out of gas on large sets: use {length} and
{get} instead in these cases.

[[EnumerableSet-length-struct-EnumerableSet-AddressSet-]]
=== length(struct EnumerableSet.AddressSet set) → uint256

Returns the number of elements on the set. O(1).

[[EnumerableSet-get-struct-EnumerableSet-AddressSet-uint256-]]
=== get(struct EnumerableSet.AddressSet set, uint256 index) → address

Returns the element stored at position `index` in the set. O(1).
Note that there are no guarantees on the ordering of values inside the
array, and it may change when more values are added or removed.

Requirements:

- `index` must be strictly less than {length}.



:Create2: pass:normal[xref:#Create2[`Create2`]]
:deploy: pass:normal[xref:#Create2-deploy-bytes32-bytes-[`deploy`]]
:computeAddress: pass:normal[xref:#Create2-computeAddress-bytes32-bytes-[`computeAddress`]]
:computeAddress: pass:normal[xref:#Create2-computeAddress-bytes32-bytes-address-[`computeAddress`]]

[[Create2]]
== `Create2`

Helper to make usage of the `CREATE2` EVM opcode easier and safer.
`CREATE2` can be used to compute in advance the address where a smart
contract will be deployed, which allows for interesting new mechanisms known
as 'counterfactual interactions'.

See the https://eips.ethereum.org/EIPS/eip-1014#motivation[EIP] for more
information.

_Available since v2.5.0._


- xref:#Create2-deploy-bytes32-bytes-[deploy(bytes32,bytes)]
- xref:#Create2-computeAddress-bytes32-bytes-[computeAddress(bytes32,bytes)]
- xref:#Create2-computeAddress-bytes32-bytes-address-[computeAddress(bytes32,bytes,address)]


[[Create2-deploy-bytes32-bytes-]]
=== deploy(bytes32 salt, bytes bytecode) → address

Deploys a contract using `CREATE2`. The address where the contract
will be deployed can be known in advance via {computeAddress}. Note that
a contract cannot be deployed twice using the same salt.

[[Create2-computeAddress-bytes32-bytes-]]
=== computeAddress(bytes32 salt, bytes bytecode) → address

Returns the address where a contract will be stored if deployed via {deploy}. Any change in the `bytecode`
or `salt` will result in a new destination address.

[[Create2-computeAddress-bytes32-bytes-address-]]
=== computeAddress(bytes32 salt, bytes bytecodeHash, address deployer) → address

Returns the address where a contract will be stored if deployed via {deploy} from a contract located at
`deployer`. If `deployer` is this contract's address, returns the same value as {computeAddress}.



:ReentrancyGuard: pass:normal[xref:#ReentrancyGuard[`ReentrancyGuard`]]
:nonReentrant: pass:normal[xref:#ReentrancyGuard-nonReentrant--[`nonReentrant`]]
:constructor: pass:normal[xref:#ReentrancyGuard-constructor--[`constructor`]]

[[ReentrancyGuard]]
== `ReentrancyGuard`

Contract module that helps prevent reentrant calls to a function.

Inheriting from `ReentrancyGuard` will make the {nonReentrant} modifier
available, which can be applied to functions to make sure there are no nested
(reentrant) calls to them.

Note that because there is a single `nonReentrant` guard, functions marked as
`nonReentrant` may not call one another. This can be worked around by making
those functions `private`, and then adding `external` `nonReentrant` entry
points to them.

TIP: If you would like to learn more about reentrancy and alternative ways
to protect against it, check out our blog post
https://blog.openzeppelin.com/reentrancy-after-istanbul/[Reentrancy After Istanbul].

_Since v2.5.0:_ this module is now much more gas efficient, given net gas
metering changes introduced in the Istanbul hardfork.

- xref:#ReentrancyGuard-nonReentrant--[nonReentrant()]

- xref:#ReentrancyGuard-constructor--[constructor()]


[[ReentrancyGuard-nonReentrant--]]
=== nonReentrant()

Prevents a contract from calling itself, directly or indirectly.
Calling a `nonReentrant` function from another `nonReentrant`
function is not supported. It is possible to prevent this from happening
by making the `nonReentrant` function external, and make it call a
`private` function that does the actual work.

[[ReentrancyGuard-constructor--]]
=== constructor()




